version: '3.3'
services:
  website:
    image: hugomods/hugo:latest
    volumes:
      - "./:/src"
    command:
      - hugo
      - server
      - -D
      - --bind=0.0.0.0
#      - --ignoreCache
    ports:
     - "1313:1313"
